project: 
  type: website
  
website: 
  title: "Dr Adamu Onu"
  navbar: 
    background: dark
    left: 
      - index.qmd
      - projects.qmd
      - courses.qmd
      - publications.qmd
      
    right: 
      - about.qmd
        
format: 
  html: 
    toc: true
    toc-depth: 2
    theme: spacelab
    css: styles.css
    
editor: source

execute: 
  freeze: auto